spring.application.name=TaskManager

spring.datasource.url=jdbc:mysql://localhost:3306/taskmanager
spring.datasource.username=root
spring.datasource.password=PokemonJ0LT30NRebu

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true